# Generated by Django 3.2.5 on 2021-07-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='index.jpeg', upload_to=''),
        ),
    ]
